server:
  port: 8195
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/surender08/sprint-cloud-config-store.git
          search-paths:
           - '*abc'



