server:
  port: 8192
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/surender08/sprint-cloud-config-store
          search-paths:
            - '*service'



